//
//  SeriesController.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "Series.h"
#import "CharacterDataWrapper.h"
#import "ComicDataWrapper.h"
#import "FormatTypeEnum.h"
#import "FormatTypeEnumHelper.h"
#import "DateDescriptorEnum.h"
#import "DateDescriptorEnumHelper.h"
#import "CreatorDataWrapper.h"
#import "EventDataWrapper.h"
#import "StoryDataWrapper.h"
#import "SeriesDataWrapper.h"

@interface SeriesController : BaseController

/**
* Completion block definition for asynchronous call to getSeriesIndividual */
typedef void (^CompletedGetSeriesIndividual)(BOOL success, HttpContext* context, Series* response, NSError* error);

/**
* Fetches a single comic series by id.
* @param    seriesId    Required parameter: Filter by series title.
*/
- (void) getSeriesIndividualAsyncWithSeriesId:(NSString*) seriesId
                completionBlock:(CompletedGetSeriesIndividual) onCompleted;

/**
* Completion block definition for asynchronous call to getSeriesCharacterWrapper */
typedef void (^CompletedGetSeriesCharacterWrapper)(BOOL success, HttpContext* context, CharacterDataWrapper* response, NSError* error);

/**
* Fetches lists of characters filtered by a series id.
* @param    seriesId    Required parameter: Filter by series title.
* @param    comics    Optional parameter: Return only characters which appear in the specified comics (accepts a comma-separated list of ids).
* @param    events    Optional parameter: Return only characters which appear comics that took place in the specified events (accepts a comma-separated list of ids).
* @param    limit    Optional parameter: Limit the result set to the specified number of resources.
* @param    modifiedSince    Optional parameter: Return only characters which have been modified since the specified date.
* @param    name    Optional parameter: Return only characters matching the specified full character name (e.g. Spider-Man).
* @param    nameStartsWith    Optional parameter: Return characters with names that begin with the specified string (e.g. Sp).
* @param    offset    Optional parameter: Skip the specified number of resources in the result set.
* @param    orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "name", "modified", "-name", "-modified")
* @param    stories    Optional parameter: Return only characters which appear the specified stories (accepts a comma-separated list of ids).
*/
- (void) getSeriesCharacterWrapperAsyncWithSeriesId:(NSString*) seriesId
                comics:(NSString*) comics
                events:(NSString*) events
                limit:(NSString*) limit
                modifiedSince:(NSString*) modifiedSince
                name:(NSString*) name
                nameStartsWith:(NSString*) nameStartsWith
                offset:(NSString*) offset
                orderBy:(NSString*) orderBy
                stories:(NSString*) stories
                completionBlock:(CompletedGetSeriesCharacterWrapper) onCompleted;

/**
* Completion block definition for asynchronous call to getComicsCollectionBySeriesId */
typedef void (^CompletedGetComicsCollectionBySeriesId)(BOOL success, HttpContext* context, ComicDataWrapper* response, NSError* error);

/**
* Fetches lists of comics filtered by a series id.
* @param    seriesId    Required parameter: Filter by series title.
* @param    characters    Optional parameter: Return only comics which feature the specified characters (accepts a comma-separated list of ids).
* @param    collaborators    Optional parameter: Return only comics in which the specified creators worked together (for example in which BOTH Stan Lee and Jack Kirby did work).
* @param    creators    Optional parameter: Return only comics which feature work by the specified creators (accepts a comma-separated list of ids).
* @param    dateDescriptor    Optional parameter: Return comics within a predefined date range.
* @param    dateRange    Optional parameter: Return comics within a predefined date range.  Dates must be specified as date1,date2 (e.g. 2013-01-01,2013-01-02).  Dates are preferably formatted as YYYY-MM-DD but may be sent as any common date format.
* @param    diamondCode    Optional parameter: Filter by diamond code.
* @param    digitalId    Optional parameter: Filter by digital comic id.
* @param    ean    Optional parameter: Filter by EAN.
* @param    events    Optional parameter: Return only comics which take place in the specified events (accepts a comma-separated list of ids).
* @param    format    Optional parameter: Filter by the issue format (e.g. comic, digital comic, hardcover). (Acceptable values are: "comic", "magazine", "trade paperback", "hardcover", "digest", "graphic novel", "digital comic", "infinite comic")
* @param    formatType    Optional parameter: Filter by the issue format type (comic or collection).
* @param    hasDigitalIssue    Optional parameter: Include only results which are available digitally. (Acceptable values are: "true")
* @param    isbn    Optional parameter: Filter by ISBN.
* @param    issn    Optional parameter: Filter by ISSN.
* @param    issueNumber    Optional parameter: Return only issues in series whose issue number matches the input.
* @param    limit    Optional parameter: Limit the result set to the specified number of resources.
* @param    modifiedSince    Optional parameter: Return only comics which have been modified since the specified date.
* @param    noVariants    Optional parameter: Exclude variant comics from the result set. (Acceptable values are: "true")
* @param    offset    Optional parameter: Skip the specified number of resources in the result set.
* @param    orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "focDate", "onsaleDate", "title", "issueNumber", "modified", "-focDate", "-onsaleDate", "-title", "-issueNumber", "-modified")
* @param    sharedAppearances    Optional parameter: Return only comics in which the specified characters appear together (for example in which BOTH Spider-Man and Wolverine appear).
* @param    startYear    Optional parameter: Return only issues in series whose start year matches the input.
* @param    stories    Optional parameter: Return only comics which contain the specified stories (accepts a comma-separated list of ids).
* @param    title    Optional parameter: Return only issues in series whose title matches the input.
* @param    titleStartsWith    Optional parameter: Return only issues in series whose title starts with the input.
* @param    upc    Optional parameter: Filter by UPC.
*/
- (void) getComicsCollectionBySeriesIdAsyncWithSeriesId:(NSString*) seriesId
                characters:(NSString*) characters
                collaborators:(NSString*) collaborators
                creators:(NSString*) creators
                dateDescriptor:(enum DateDescriptorEnum) dateDescriptor
                dateRange:(NSString*) dateRange
                diamondCode:(NSString*) diamondCode
                digitalId:(NSString*) digitalId
                ean:(NSString*) ean
                events:(NSString*) events
                format:(NSString*) format
                formatType:(enum FormatTypeEnum) formatType
                hasDigitalIssue:(NSString*) hasDigitalIssue
                isbn:(NSString*) isbn
                issn:(NSString*) issn
                issueNumber:(NSString*) issueNumber
                limit:(NSString*) limit
                modifiedSince:(NSString*) modifiedSince
                noVariants:(NSString*) noVariants
                offset:(NSString*) offset
                orderBy:(NSString*) orderBy
                sharedAppearances:(NSString*) sharedAppearances
                startYear:(NSString*) startYear
                stories:(NSString*) stories
                title:(NSString*) title
                titleStartsWith:(NSString*) titleStartsWith
                upc:(NSString*) upc
                completionBlock:(CompletedGetComicsCollectionBySeriesId) onCompleted;

/**
* Completion block definition for asynchronous call to getCreatorCollectionBySeriesId */
typedef void (^CompletedGetCreatorCollectionBySeriesId)(BOOL success, HttpContext* context, CreatorDataWrapper* response, NSError* error);

/**
* Fetches lists of creators filtered by a series id.
* @param    seriesId    Required parameter: Filter by series title.
* @param    comics    Optional parameter: Return only creators who worked on in the specified comics (accepts a comma-separated list of ids).
* @param    events    Optional parameter: Return only creators who worked on comics that took place in the specified events (accepts a comma-separated list of ids).
* @param    firstName    Optional parameter: Filter by creator first name (e.g. brian).
* @param    firstNameStartsWith    Optional parameter: Filter by creator first names that match critera (e.g. B, St L).
* @param    lastName    Optional parameter: Filter by creator last name (e.g. Bendis).
* @param    lastNameStartsWith    Optional parameter: Filter by creator last names that match critera (e.g. Ben).
* @param    limit    Optional parameter: Limit the result set to the specified number of resources.
* @param    middleName    Optional parameter: Filter by creator middle name (e.g. Michael).
* @param    middleNameStartsWith    Optional parameter: Filter by creator middle names that match critera (e.g. Mi).
* @param    modifiedSince    Optional parameter: Return only creators which have been modified since the specified date.
* @param    nameStartsWith    Optional parameter: Filter by creator names that match critera (e.g. B, St L).
* @param    offset    Optional parameter: Skip the specified number of resources in the result set.
* @param    orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "lastName", "firstName", "middleName", "suffix", "modified", "-lastName", "-firstName", "-middleName", "-suffix", "-modified")
* @param    stories    Optional parameter: Return only creators who worked on the specified stories (accepts a comma-separated list of ids).
* @param    suffix    Optional parameter: Filter by suffix or honorific (e.g. Jr., Sr.).
*/
- (void) getCreatorCollectionBySeriesIdAsyncWithSeriesId:(NSString*) seriesId
                comics:(NSString*) comics
                events:(NSString*) events
                firstName:(NSString*) firstName
                firstNameStartsWith:(NSString*) firstNameStartsWith
                lastName:(NSString*) lastName
                lastNameStartsWith:(NSString*) lastNameStartsWith
                limit:(NSString*) limit
                middleName:(NSString*) middleName
                middleNameStartsWith:(NSString*) middleNameStartsWith
                modifiedSince:(NSString*) modifiedSince
                nameStartsWith:(NSString*) nameStartsWith
                offset:(NSString*) offset
                orderBy:(NSString*) orderBy
                stories:(NSString*) stories
                suffix:(NSString*) suffix
                completionBlock:(CompletedGetCreatorCollectionBySeriesId) onCompleted;

/**
* Completion block definition for asynchronous call to getEventsCollectionBySeriesId */
typedef void (^CompletedGetEventsCollectionBySeriesId)(BOOL success, HttpContext* context, EventDataWrapper* response, NSError* error);

/**
* Fetches lists of events filtered by a series id.
* @param    seriesId    Required parameter: Filter by series title.
* @param    characters    Optional parameter: Return only events which feature the specified characters (accepts a comma-separated list of ids).
* @param    comics    Optional parameter: Return only events which take place in the specified comics (accepts a comma-separated list of ids).
* @param    creators    Optional parameter: Return only events which feature work by the specified creators (accepts a comma-separated list of ids).
* @param    limit    Optional parameter: Limit the result set to the specified number of resources.
* @param    modifiedSince    Optional parameter: Return only events which have been modified since the specified date.
* @param    name    Optional parameter: Filter the event list by name.
* @param    nameStartsWith    Optional parameter: Return events with names that begin with the specified string (e.g. Sp).
* @param    offset    Optional parameter: Skip the specified number of resources in the result set.
* @param    orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "name", "startDate", "modified", "-name", "-startDate", "-modified")
* @param    stories    Optional parameter: Return only events which contain the specified stories (accepts a comma-separated list of ids).
*/
- (void) getEventsCollectionBySeriesIdAsyncWithSeriesId:(NSString*) seriesId
                characters:(NSString*) characters
                comics:(NSString*) comics
                creators:(NSString*) creators
                limit:(NSString*) limit
                modifiedSince:(NSString*) modifiedSince
                name:(NSString*) name
                nameStartsWith:(NSString*) nameStartsWith
                offset:(NSString*) offset
                orderBy:(NSString*) orderBy
                stories:(NSString*) stories
                completionBlock:(CompletedGetEventsCollectionBySeriesId) onCompleted;

/**
* Completion block definition for asynchronous call to getSeriesStoryCollection */
typedef void (^CompletedGetSeriesStoryCollection)(BOOL success, HttpContext* context, StoryDataWrapper* response, NSError* error);

/**
* Fetches lists of stories filtered by a series id.
* @param    seriesId    Required parameter: Filter by series title.
* @param    characters    Optional parameter: Return only stories which feature the specified characters (accepts a comma-separated list of ids).
* @param    comics    Optional parameter: Return only stories contained in the specified (accepts a comma-separated list of ids).
* @param    creators    Optional parameter: Return only stories which feature work by the specified creators (accepts a comma-separated list of ids).
* @param    events    Optional parameter: Return only stories which take place during the specified events (accepts a comma-separated list of ids).
* @param    limit    Optional parameter: Limit the result set to the specified number of resources.
* @param    modifiedSince    Optional parameter: Return only stories which have been modified since the specified date.
* @param    offset    Optional parameter: Skip the specified number of resources in the result set.
* @param    orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "id", "modified", "-id", "-modified")
*/
- (void) getSeriesStoryCollectionAsyncWithSeriesId:(NSString*) seriesId
                characters:(NSString*) characters
                comics:(NSString*) comics
                creators:(NSString*) creators
                events:(NSString*) events
                limit:(NSString*) limit
                modifiedSince:(NSString*) modifiedSince
                offset:(NSString*) offset
                orderBy:(NSString*) orderBy
                completionBlock:(CompletedGetSeriesStoryCollection) onCompleted;

/**
* Completion block definition for asynchronous call to getSeriesCollection */
typedef void (^CompletedGetSeriesCollection)(BOOL success, HttpContext* context, SeriesDataWrapper* response, NSError* error);

/**
* Fetches lists of series.
* @param    characters    Optional parameter: Return only series which feature the specified characters (accepts a comma-separated list of ids).
* @param    comics    Optional parameter: Return only series which contain the specified comics (accepts a comma-separated list of ids).
* @param    contains    Optional parameter: Return only series containing one or more comics with the specified format. (Acceptable values are: "comic", "magazine", "trade paperback", "hardcover", "digest", "graphic novel", "digital comic", "infinite comic")
* @param    creators    Optional parameter: Return only series which feature work by the specified creators (accepts a comma-separated list of ids).
* @param    events    Optional parameter: Return only series which have comics that take place during the specified events (accepts a comma-separated list of ids).
* @param    limit    Optional parameter: Limit the result set to the specified number of resources.
* @param    modifiedSince    Optional parameter: Return only series which have been modified since the specified date.
* @param    offset    Optional parameter: Skip the specified number of resources in the result set.
* @param    orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "title", "modified", "startYear", "-title", "-modified", "-startYear")
* @param    seriesType    Optional parameter: Filter the series by publication frequency type. (Acceptable values are: "collection", "one shot", "limited", "ongoing")
* @param    startYear    Optional parameter: Return only series matching the specified start year.
* @param    stories    Optional parameter: Return only series which contain the specified stories (accepts a comma-separated list of ids).
* @param    title    Optional parameter: Return only series matching the specified title.
* @param    titleStartsWith    Optional parameter: Return series with titles that begin with the specified string (e.g. Sp).
*/
- (void) getSeriesCollectionAsyncWithCharacters:(NSString*) characters
                comics:(NSString*) comics
                contains:(NSString*) contains
                creators:(NSString*) creators
                events:(NSString*) events
                limit:(NSString*) limit
                modifiedSince:(NSString*) modifiedSince
                offset:(NSString*) offset
                orderBy:(NSString*) orderBy
                seriesType:(NSString*) seriesType
                startYear:(NSString*) startYear
                stories:(NSString*) stories
                title:(NSString*) title
                titleStartsWith:(NSString*) titleStartsWith
                completionBlock:(CompletedGetSeriesCollection) onCompleted;

@end