//
//  Character.m
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#import "Character.h"

@implementation Character

/**
* A resource list containing comics which feature this character.
*/
@synthesize comics;

/**
* A short bio or description of the character.
*/
@synthesize description;

/**
* A resource list of events in which this character appears.
*/
@synthesize events;

/**
* The unique ID of the character resource.
*/
@synthesize mid;

/**
* The date the resource was most recently modified.
*/
@synthesize modified;

/**
* The name of the character.
*/
@synthesize name;

/**
* The canonical URL identifier for this resource.
*/
@synthesize resourceURI;

/**
* A resource list of series in which this character appears.
*/
@synthesize series;

/**
* A resource list of stories in which this character appears.
*/
@synthesize stories;

/**
* The representative image for this character.
*/
@synthesize thumbnail;

/**
* A set of public web site URLs for the resource.
*/
@synthesize urls;

/**
 * For deserialization of enum UrlModel type property from NSArray
 */
 -(void)setUrlsWithNSArray:(NSArray*) array
{
	NSError* err;
    urls = [UrlModel arrayOfModelsFromDictionaries:array error:&err];
	if(err){
		NSLog(@"Failed to deserialise urls property");
	}
}


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"comics": @"comics",
        @"description": @"description",
        @"events": @"events",
        @"id": @"mid",
        @"modified": @"modified",
        @"name": @"name",
        @"resourceURI": @"resourceURI",
        @"series": @"series",
        @"stories": @"stories",
        @"thumbnail": @"thumbnail",
        @"urls": @"urls"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end