//
//  CharacterSummary.m
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#import "CharacterSummary.h"

@implementation CharacterSummary

/**
* The full name of the character.
*/
@synthesize name;

/**
* The path to the individual character resource.
*/
@synthesize resourceURI;

/**
* The role of the creator in the parent entity.
*/
@synthesize role;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"name": @"name",
        @"resourceURI": @"resourceURI",
        @"role": @"role"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end