//
//  Character.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_CHARACTER
#define APIMATIC_CHARACTER

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "ComicList.h"
#import "EventList.h"
#import "SeriesList.h"
#import "StoryList.h"
#import "Thumbnail.h"
#import "UrlModel.h"


//protocol defined for deserialization of JSON
@protocol Character
@end

@interface Character : JSONModel

/**
* A resource list containing comics which feature this character.
*/
@property ComicList* comics;

/**
* A short bio or description of the character.
*/
@property NSString* description;

/**
* A resource list of events in which this character appears.
*/
@property EventList* events;

/**
* The unique ID of the character resource.
*/
@property int mid;

/**
* The date the resource was most recently modified.
*/
@property NSDate* modified;

/**
* The name of the character.
*/
@property NSString* name;

/**
* The canonical URL identifier for this resource.
*/
@property NSString* resourceURI;

/**
* A resource list of series in which this character appears.
*/
@property SeriesList* series;

/**
* A resource list of stories in which this character appears.
*/
@property StoryList* stories;

/**
* The representative image for this character.
*/
@property Thumbnail* thumbnail;

/**
* A set of public web site URLs for the resource.
*/
@property NSArray<UrlModel*> * urls;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif