//
//  ComicList.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_COMICLIST
#define APIMATIC_COMICLIST

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "ComicSummary.h"


//protocol defined for deserialization of JSON
@protocol ComicList
@end

@interface ComicList : JSONModel

/**
* The number of total available issues in this list. Will always be greater than or equal to the "returned" value.
*/
@property int available;

/**
* The path to the full list of issues in this collection.
*/
@property NSString* collectionURI;

/**
* The list of returned issues in this collection.
*/
@property NSArray<ComicSummary*> * items;

/**
* The number of issues returned in this collection (up to 20).
*/
@property int returned;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif