//
//  CreatorList.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_CREATORLIST
#define APIMATIC_CREATORLIST

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "CreatorSummary.h"


//protocol defined for deserialization of JSON
@protocol CreatorList
@end

@interface CreatorList : JSONModel

/**
* The number of total available creators in this list. Will always be greater than or equal to the "returned" value.
*/
@property int available;

/**
* The path to the full list of creators in this collection.
*/
@property NSString* collectionURI;

/**
* The list of returned creators in this collection.
*/
@property NSArray<CreatorSummary*> * items;

/**
* The number of creators returned in this collection (up to 20).
*/
@property int returned;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif