//
//  Creator.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_CREATOR
#define APIMATIC_CREATOR

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "ComicList.h"
#import "EventList.h"
#import "SeriesList.h"
#import "StoryList.h"
#import "Thumbnail.h"
#import "UrlModel.h"


//protocol defined for deserialization of JSON
@protocol Creator
@end

@interface Creator : JSONModel

/**
* A resource list containing the comics which feature work by this creator.
*/
@property ComicList* comics;

/**
* A resource list containing the events which feature work by this creator.
*/
@property EventList* events;

/**
* The first name of the creator.
*/
@property NSString* firstName;

/**
* The full name of the creator (a space-separated concatenation of the above four fields).
*/
@property NSString* fullName;

/**
* The unique ID of the creator resource.
*/
@property int mid;

/**
* The last name of the creator.
*/
@property NSString* lastName;

/**
* The middle name of the creator.
*/
@property NSString* middleName;

/**
* The date the resource was most recently modified.
*/
@property NSDate* modified;

/**
* The canonical URL identifier for this resource.
*/
@property NSString* resourceURI;

/**
* A resource list containing the series which feature work by this creator.
*/
@property SeriesList* series;

/**
* A resource list containing the stories which feature work by this creator.
*/
@property StoryList* stories;

/**
* The suffix or honorific for the creator.
*/
@property NSString* suffix;

/**
* The representative image for this creator.
*/
@property Thumbnail* thumbnail;

/**
* A set of public web site URLs for the resource.
*/
@property NSArray<UrlModel*> * urls;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif