//
//  Creator.m
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#import "Creator.h"

@implementation Creator

/**
* A resource list containing the comics which feature work by this creator.
*/
@synthesize comics;

/**
* A resource list containing the events which feature work by this creator.
*/
@synthesize events;

/**
* The first name of the creator.
*/
@synthesize firstName;

/**
* The full name of the creator (a space-separated concatenation of the above four fields).
*/
@synthesize fullName;

/**
* The unique ID of the creator resource.
*/
@synthesize mid;

/**
* The last name of the creator.
*/
@synthesize lastName;

/**
* The middle name of the creator.
*/
@synthesize middleName;

/**
* The date the resource was most recently modified.
*/
@synthesize modified;

/**
* The canonical URL identifier for this resource.
*/
@synthesize resourceURI;

/**
* A resource list containing the series which feature work by this creator.
*/
@synthesize series;

/**
* A resource list containing the stories which feature work by this creator.
*/
@synthesize stories;

/**
* The suffix or honorific for the creator.
*/
@synthesize suffix;

/**
* The representative image for this creator.
*/
@synthesize thumbnail;

/**
* A set of public web site URLs for the resource.
*/
@synthesize urls;

/**
 * For deserialization of enum UrlModel type property from NSArray
 */
 -(void)setUrlsWithNSArray:(NSArray*) array
{
	NSError* err;
    urls = [UrlModel arrayOfModelsFromDictionaries:array error:&err];
	if(err){
		NSLog(@"Failed to deserialise urls property");
	}
}


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"comics": @"comics",
        @"events": @"events",
        @"firstName": @"firstName",
        @"fullName": @"fullName",
        @"id": @"mid",
        @"lastName": @"lastName",
        @"middleName": @"middleName",
        @"modified": @"modified",
        @"resourceURI": @"resourceURI",
        @"series": @"series",
        @"stories": @"stories",
        @"suffix": @"suffix",
        @"thumbnail": @"thumbnail",
        @"urls": @"urls"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end