//
//  CreatorSummary.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_CREATORSUMMARY
#define APIMATIC_CREATORSUMMARY

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreatorSummary
@end

@interface CreatorSummary : JSONModel

/**
* The full name of the creator.
*/
@property NSString* name;

/**
* The path to the individual creator resource.
*/
@property NSString* resourceURI;

/**
* The role of the creator in the parent entity.
*/
@property NSString* role;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif