//
//  DateDescriptorEnum.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_DATEDESCRIPTORENUM
#define APIMATIC_DATEDESCRIPTORENUM
 
enum DateDescriptorEnum
{
        DateDescriptorEnumLastWeek, //TODO: Write general description for this method
        DateDescriptorEnumNextWeek, //TODO: Write general description for this method
        DateDescriptorEnumThisMonth, //TODO: Write general description for this method
        DateDescriptorEnumThisWeek, //TODO: Write general description for this method
};

#endif