//
//  DateDescriptorEnum.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_DATEDESCRIPTORENUMHELPER
#define APIMATIC_DATEDESCRIPTORENUMHELPER

#include "DateDescriptorEnum.h"

/**
* Helper class interface for DateDescriptorEnum to NSString conversion
*/
@interface DateDescriptorEnumHelper : NSObject

+(id) stringFromDateDescriptorEnum:(enum DateDescriptorEnum) dateDescriptorEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromDateDescriptorEnumArray:(NSArray<NSNumber*>*) array;


+(enum DateDescriptorEnum) dateDescriptorEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) dateDescriptorEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif