//
//  Event.m
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#import "Event.h"

@implementation Event

/**
* A resource list containing the characters which appear in this event.
*/
@synthesize characters;

/**
* A resource list containing the comics in this event.
*/
@synthesize comics;

/**
* A resource list containing creators whose work appears in this event.
*/
@synthesize creators;

/**
* A description of the event.
*/
@synthesize description;

/**
* The date of publication of the last issue in this event.
*/
@synthesize mend;

/**
* The unique ID of the event resource.
*/
@synthesize mid;

/**
* The date the resource was most recently modified.
*/
@synthesize modified;

/**
* A summary representation of the event which follows this event.
*/
@synthesize next;

/**
* A summary representation of the event which preceded this event.
*/
@synthesize previous;

/**
* The canonical URL identifier for this resource.
*/
@synthesize resourceURI;

/**
* A resource list containing the series in this event.
*/
@synthesize series;

/**
* The date of publication of the first issue in this event.
*/
@synthesize start;

/**
* A resource list containing the stories in this event.
*/
@synthesize stories;

/**
* The representative image for this event.
*/
@synthesize thumbnail;

/**
* The title of the event.
*/
@synthesize title;

/**
* A set of public web site URLs for the event.
*/
@synthesize urls;

/**
 * For deserialization of enum UrlModel type property from NSArray
 */
 -(void)setUrlsWithNSArray:(NSArray*) array
{
	NSError* err;
    urls = [UrlModel arrayOfModelsFromDictionaries:array error:&err];
	if(err){
		NSLog(@"Failed to deserialise urls property");
	}
}


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"characters": @"characters",
        @"comics": @"comics",
        @"creators": @"creators",
        @"description": @"description",
        @"end": @"mend",
        @"id": @"mid",
        @"modified": @"modified",
        @"next": @"next",
        @"previous": @"previous",
        @"resourceURI": @"resourceURI",
        @"series": @"series",
        @"start": @"start",
        @"stories": @"stories",
        @"thumbnail": @"thumbnail",
        @"title": @"title",
        @"urls": @"urls"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end