//
//  EventList.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_EVENTLIST
#define APIMATIC_EVENTLIST

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "EventSummary.h"


//protocol defined for deserialization of JSON
@protocol EventList
@end

@interface EventList : JSONModel

/**
* The number of total available events in this list. Will always be greater than or equal to the "returned" value.
*/
@property int available;

/**
* The path to the full list of events in this collection.
*/
@property NSString* collectionURI;

/**
* The list of returned events in this collection.
*/
@property NSArray<EventSummary*> * items;

/**
* The number of events returned in this collection (up to 20).
*/
@property int returned;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif