//
//  Event.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_EVENT
#define APIMATIC_EVENT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "CharacterList.h"
#import "ComicList.h"
#import "CreatorList.h"
#import "EventSummary.h"
#import "SeriesList.h"
#import "StoryList.h"
#import "Thumbnail.h"
#import "UrlModel.h"


//protocol defined for deserialization of JSON
@protocol Event
@end

@interface Event : JSONModel

/**
* A resource list containing the characters which appear in this event.
*/
@property CharacterList* characters;

/**
* A resource list containing the comics in this event.
*/
@property ComicList* comics;

/**
* A resource list containing creators whose work appears in this event.
*/
@property CreatorList* creators;

/**
* A description of the event.
*/
@property NSString* description;

/**
* The date of publication of the last issue in this event.
*/
@property NSDate* mend;

/**
* The unique ID of the event resource.
*/
@property int mid;

/**
* The date the resource was most recently modified.
*/
@property NSDate* modified;

/**
* A summary representation of the event which follows this event.
*/
@property EventSummary* next;

/**
* A summary representation of the event which preceded this event.
*/
@property EventSummary* previous;

/**
* The canonical URL identifier for this resource.
*/
@property NSString* resourceURI;

/**
* A resource list containing the series in this event.
*/
@property SeriesList* series;

/**
* The date of publication of the first issue in this event.
*/
@property NSDate* start;

/**
* A resource list containing the stories in this event.
*/
@property StoryList* stories;

/**
* The representative image for this event.
*/
@property Thumbnail* thumbnail;

/**
* The title of the event.
*/
@property NSString* title;

/**
* A set of public web site URLs for the event.
*/
@property NSArray<UrlModel*> * urls;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif