//
//  FormatTypeEnum.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_FORMATTYPEENUM
#define APIMATIC_FORMATTYPEENUM
 
enum FormatTypeEnum
{
        FormatTypeEnumCollection, //TODO: Write general description for this method
        FormatTypeEnumComic, //TODO: Write general description for this method
};

#endif