//
//  FormatTypeEnum.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_FORMATTYPEENUMHELPER
#define APIMATIC_FORMATTYPEENUMHELPER

#include "FormatTypeEnum.h"

/**
* Helper class interface for FormatTypeEnum to NSString conversion
*/
@interface FormatTypeEnumHelper : NSObject

+(id) stringFromFormatTypeEnum:(enum FormatTypeEnum) formatTypeEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromFormatTypeEnumArray:(NSArray<NSNumber*>*) array;


+(enum FormatTypeEnum) formatTypeEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) formatTypeEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif