//
//  Series.m
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#import "Series.h"

@implementation Series

/**
* A resource list containing characters which appear in comics in this series.
*/
@synthesize characters;

/**
* A resource list containing comics in this series.
*/
@synthesize comics;

/**
* A resource list of creators whose work appears in comics in this series.
*/
@synthesize creators;

/**
* A description of the series.
*/
@synthesize description;

/**
* The last year of publication for the series (conventionally, 2099 for ongoing series) .
*/
@synthesize endYear;

/**
* A resource list containing events which take place in comics in this series.
*/
@synthesize events;

/**
* The unique ID of the series resource.
*/
@synthesize mid;

/**
* The date the resource was most recently modified.
*/
@synthesize modified;

/**
* A summary representation of the series which follows this series.
*/
@synthesize next;

/**
* A summary representation of the series which preceded this series.
*/
@synthesize previous;

/**
* The age-appropriateness rating for the series.
*/
@synthesize rating;

/**
* The canonical URL identifier for this resource.
*/
@synthesize resourceURI;

/**
* The first year of publication for the series.
*/
@synthesize startYear;

/**
* A resource list containing stories which occur in comics in this series.
*/
@synthesize stories;

/**
* The representative image for this series.
*/
@synthesize thumbnail;

/**
* The canonical title of the series.
*/
@synthesize title;

/**
* A set of public web site URLs for the resource.
*/
@synthesize urls;

/**
 * For deserialization of enum UrlModel type property from NSArray
 */
 -(void)setUrlsWithNSArray:(NSArray*) array
{
	NSError* err;
    urls = [UrlModel arrayOfModelsFromDictionaries:array error:&err];
	if(err){
		NSLog(@"Failed to deserialise urls property");
	}
}


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"characters": @"characters",
        @"comics": @"comics",
        @"creators": @"creators",
        @"description": @"description",
        @"endYear": @"endYear",
        @"events": @"events",
        @"id": @"mid",
        @"modified": @"modified",
        @"next": @"next",
        @"previous": @"previous",
        @"rating": @"rating",
        @"resourceURI": @"resourceURI",
        @"startYear": @"startYear",
        @"stories": @"stories",
        @"thumbnail": @"thumbnail",
        @"title": @"title",
        @"urls": @"urls"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end