//
//  Series.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_SERIES
#define APIMATIC_SERIES

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "CharacterList.h"
#import "ComicList.h"
#import "CreatorList.h"
#import "EventList.h"
#import "SeriesSummary.h"
#import "StoryList.h"
#import "Thumbnail.h"
#import "UrlModel.h"


//protocol defined for deserialization of JSON
@protocol Series
@end

@interface Series : JSONModel

/**
* A resource list containing characters which appear in comics in this series.
*/
@property CharacterList* characters;

/**
* A resource list containing comics in this series.
*/
@property ComicList* comics;

/**
* A resource list of creators whose work appears in comics in this series.
*/
@property CreatorList* creators;

/**
* A description of the series.
*/
@property NSString* description;

/**
* The last year of publication for the series (conventionally, 2099 for ongoing series) .
*/
@property int endYear;

/**
* A resource list containing events which take place in comics in this series.
*/
@property EventList* events;

/**
* The unique ID of the series resource.
*/
@property int mid;

/**
* The date the resource was most recently modified.
*/
@property NSDate* modified;

/**
* A summary representation of the series which follows this series.
*/
@property SeriesSummary* next;

/**
* A summary representation of the series which preceded this series.
*/
@property SeriesSummary* previous;

/**
* The age-appropriateness rating for the series.
*/
@property NSString* rating;

/**
* The canonical URL identifier for this resource.
*/
@property NSString* resourceURI;

/**
* The first year of publication for the series.
*/
@property int startYear;

/**
* A resource list containing stories which occur in comics in this series.
*/
@property StoryList* stories;

/**
* The representative image for this series.
*/
@property Thumbnail* thumbnail;

/**
* The canonical title of the series.
*/
@property NSString* title;

/**
* A set of public web site URLs for the resource.
*/
@property NSArray<UrlModel*> * urls;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif