//
//  Story.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_STORY
#define APIMATIC_STORY

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "CharacterList.h"
#import "ComicList.h"
#import "CreatorList.h"
#import "EventList.h"
#import "ComicSummary.h"
#import "SeriesList.h"
#import "Thumbnail.h"


//protocol defined for deserialization of JSON
@protocol Story
@end

@interface Story : JSONModel

/**
* A resource list of characters which appear in this story.
*/
@property CharacterList* characters;

/**
* A resource list containing comics in which this story takes place.
*/
@property ComicList* comics;

/**
* A resource list of creators who worked on this story.
*/
@property CreatorList* creators;

/**
* A short description of the story.
*/
@property NSString* description;

/**
* A resource list of the events in which this story appears.
*/
@property EventList* events;

/**
* The unique ID of the story resource.
*/
@property int mid;

/**
* The date the resource was most recently modified.
*/
@property NSDate* modified;

/**
* A summary representation of the issue in which this story was originally published.
*/
@property ComicSummary* originalissue;

/**
* The canonical URL identifier for this resource.
*/
@property NSString* resourceURI;

/**
* A resource list containing series in which this story appears.
*/
@property SeriesList* series;

/**
* The representative image for this story.
*/
@property Thumbnail* thumbnail;

/**
* The story title.
*/
@property NSString* title;

/**
* The story type e.g. interior story, cover, text story.
*/
@property NSString* type;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif