//
//  StoryList.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_STORYLIST
#define APIMATIC_STORYLIST

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "StorySummary.h"


//protocol defined for deserialization of JSON
@protocol StoryList
@end

@interface StoryList : JSONModel

/**
* The number of total available stories in this list. Will always be greater than or equal to the "returned" value.
*/
@property int available;

/**
* The path to the full list of stories in this collection.
*/
@property NSString* collectionURI;

/**
* The list of returned stories in this collection.
*/
@property NSArray<StorySummary*> * items;

/**
* The number of stories returned in this collection (up to 20).
*/
@property int returned;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif