//
//  StorySummary.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_STORYSUMMARY
#define APIMATIC_STORYSUMMARY

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol StorySummary
@end

@interface StorySummary : JSONModel

/**
* The canonical name of the story.
*/
@property NSString* name;

/**
* The path to the individual story resource.
*/
@property NSString* resourceURI;

/**
* The type of the story (interior or cover).
*/
@property NSString* type;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif