//
//  TextObject.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef APIMATIC_TEXTOBJECT
#define APIMATIC_TEXTOBJECT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol TextObject
@end

@interface TextObject : JSONModel

/**
* The IETF language tag denoting the language the text object is written in.
*/
@property NSString* language;

/**
* The text.
*/
@property NSString* text;

/**
* The canonical type of the text object (e.g. solicit text, preview text, etc.).
*/
@property NSString* type;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif