//
//  Configuration.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#ifndef MarvelComics_Configuration_h
#define MarvelComics_Configuration_h

@interface Configuration : NSObject

/** The base Uri for API calls */
+(NSString*) BaseUri;

+(NSString*) Referer;

+(NSString*) Apikey;


@end

#endif
