//
//  Configuration.m
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//
#import "Configuration.h"

@implementation Configuration

/** The base Uri for API calls */
+(NSString*) BaseUri
{
    return @"http://gateway.marvel.com/v1/public";
}

+(NSString*) Referer
{
    return [[NSBundle mainBundle] objectForInfoDictionaryKey:@"Referer"];
}

+(NSString*) Apikey
{
    return @"";
}


@end