//
//  JSONValueTransformer+NSDate.h
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//

#import "JSONValueTransformer.h"
#import "ISO8601DateFormatter.h"

@interface JSONValueTransformer (NSDate)

-(NSDate*) NSDateFromNSString:(NSString*)string;

@end
