//
//  JSONValueTransformer+NSDate.m
//  MarvelComics
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
//

#import "JSONValueTransformer+NSDate.h"

@implementation JSONValueTransformer (NSDate)

-(NSDate*) NSDateFromNSString:(NSString*)string
{
    ISO8601DateFormatter *dateFormatter = [[ISO8601DateFormatter alloc] init];
    NSDate *date = [dateFormatter dateFromString:string];
    return date;
}

@end
